FROM node:20-alpine AS builder

WORKDIR /app

COPY frontend-web/package*.json ./
RUN npm ci

COPY frontend-web/ ./
RUN npm run build

FROM caddy:2-alpine

USER root
RUN apk add --no-cache libcap \
    && setcap -r /usr/bin/caddy || true

COPY Caddyfile /etc/caddy/Caddyfile
COPY --from=builder /app/dist /usr/share/caddy

EXPOSE 10000
